name: Build and Release Ukrainian Localization

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # Дозвіл на запис у репозиторій

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: SlayThePrincess_UA_Installer-Windows.exe
            spec_file: stp-ua.spec
          - os: macos-latest
            artifact_name: SlayThePrincess_UA_Installer-MacOS.zip
            spec_file: stp-ua-mac.spec

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build installer
        run: |
          pyinstaller ${{ matrix.spec_file }} --noconfirm --clean

      - name: Prepare artifact
        run: |
          mkdir -p release
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp dist/*.exe release/${{ matrix.artifact_name }}
          else
            cd dist
            ditto -c -k --sequesterRsrc --keepParent *.app ../release/${{ matrix.artifact_name }}
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Ukrainian Localization ${{ github.ref_name }}"
          body: "Ukrainian language pack for Slay the Princess"
          files: |
            release/${{ matrix.artifact_name }}
            