name: Build and Release Ukrainian Localization

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          
      - name: Build Windows installer
        run: |
          pyinstaller stp-ua.spec --noconfirm --clean
          
      - name: Package Windows installer
        run: |
          mkdir -p release
          Copy-Item "dist\*.exe" -Destination "release\SlayThePrincess_UA_Windows.exe"
          
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: release/SlayThePrincess_UA_Windows.exe

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          
      - name: Build macOS app
        run: |
          pyinstaller stp-ua-mac.spec --noconfirm --clean
          
      - name: Debug dist contents
        run: |
          echo "Dist directory contents:"
          ls -R dist
          
      - name: Package macOS app
        run: |
          mkdir -p release
          cd dist
          app_name=$(ls -d *.app)
          echo "Found app: $app_name"
          ditto -c -k --sequesterRsrc --keepParent "$app_name" ../release/SlayThePrincess_UA_MacOS.zip
          
      - uses: actions/upload-artifact@v4
        with:
          name: MacOS-Installer
          path: release/SlayThePrincess_UA_MacOS.zip

  release:
    needs: [windows, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release
          
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Ukrainian Localization ${{ github.ref_name }}"
          files: |
            release/SlayThePrincess_UA_Windows.exe
            release/SlayThePrincess_UA_MacOS.zip