name: Build and Release Ukrainian Localization

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: SlayThePrincess_UA_Installer.exe
            spec_file: stp-ua.spec
          - os: macos-latest
            artifact_name: SlayThePrincess_UA_Installer.app.zip
            spec_file: stp-ua-mac.spec

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build installer
        run: |
          pyinstaller ${{ matrix.spec_file }} --noconfirm --clean

      - name: Prepare artifacts
        run: |
          mkdir -p release
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cd dist
            cp *.exe ../release/${{ matrix.artifact_name }}
          else
            cd dist
            app_name=$(ls -d *.app)
            ditto -c -k --sequesterRsrc --keepParent "$app_name" ../release/${{ matrix.artifact_name }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: release/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Ukrainian Localization ${{ github.ref_name }}"
          body: "Ukrainian language pack for Slay the Princess"
          files: |
            release/SlayThePrincess_UA_Installer.exe
            release/SlayThePrincess_UA_Installer.app.zip